name: cached_storage
description: A storage addon for cached_query. Built on top of the Sqflite package.
version: 3.2.5
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/

funding:
  - https://github.com/sponsors/D-James-GH

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query: ^3.5.0
  sqflite: ^2.3.3+1
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.8
  sqflite_common: ^2.5.0
  mockito: ^5.4.5
  build_runner:
