name: cached_storage
description: A storage addon for cached_query. Built on top of the Sqflite package.
version: 0.2.0+3
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query: 0.5.0+1
  sqflite: ^2.2.3
  path: ^1.8.2


dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.0
  sqflite_common: ^2.4.1
  mockito: ^5.3.2
  build_runner:
