name: devtools_extension
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: 0.0.9
  devtools_app_shared: 0.0.5
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  vm_service: ^11.10.0
  logger: ^2.0.2+1
  cached_query: ^2.0.0-dev.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
flutter:
  uses-material-design: true

