name: cached_query_flutter
description: Assortment of builders and addons for use with Cached Query in flutter.
version: 3.1.0-dev.0
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/

funding:
  - https://github.com/sponsors/D-James-GH

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query: ^3.1.0-dev.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  connectivity_plus_platform_interface: ^2.0.1
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
