name: cached_query
description: A simple library for dealing with server state in dart and flutter.
version: 0.5.0
repository: https://github.com/D-James-GH/cached_query
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.7
  meta: ^1.8.0
  collection: ^1.16.0

dev_dependencies:
  test: ^1.22.0
  flutter_lints: ^2.0.1
  build_runner:
  mockito: ^5.3.2

